### ISSUE TITLE
Broken Dash Manager?

### ISSUE THREAD

**Issue by H4rrisonFart** [DevOculus-Meta-Quest/Oculus-VR-Dash-Manager#6] opened 2023-11-21 21:21 UTC
![brknVRdash](https://github.com/DevOculus-Meta-Quest/Oculus-VR-Dash-Manager/assets/151662745/3ee41a3b-0ca4-4530-98db-06f48adb9af6)
Hi, my Dashboard looks like this. Idk why? Also it only works with official Oculus Dash but if the Dash Manager is opened the loading Status of my Devices (Quest 3 + Controller) in the offical Oculus Dash isn't shown anymore (but it's green for connected).  Update Checker and Diagnostics seems to be fine. Avast and Firewall didn't block anything. The regular Way without both Tools all worked fine. But Dash Manager + Oculus Killer seems to made things worse. I think the Error is on my Side but i don't know what i made wrong...any Suggestions?

**Comment by Eliminater74** [comment] 2023-11-23 02:38
Wow, thats the first I seen this.. Did you check the logs, should be a LOGfile in the same directory you run this from.
I have not received any other messages or notices from anyone else having this issue. its very weird to me. What system are you running this one?  its like your missing the fonts and resources that work this. are you on a custom install of Windows? Like maybe you removed alot of fonts or something? Can you verify this on a friends computer or some other system and see if it does the same thing?, I mean your missing something. I can see that its working.. If OculusKiller works perfect and you dont need the Dash Manager then you dont need it. but if you truly want to get this working.. Please let me know any other info you can give me.

I think I have seen something like this before. just been a long time and cant remember what caused it.. and when I said I seen something like this before, I dont mean with my current project. I mean with some other software some years back..

But it does look like your missing some resources.. are all your NET frameworks updated? plz get back with me ASAP..

**Comment by Eliminater74** [comment] 2023-11-23 02:41
Based on the description provided and without access to specific error messages or the ability to directly troubleshoot the application, here are a few potential causes for the issue with the Oculus VR Dash Manager as described:

1. **.NET Framework Compatibility**: If the application was built for a specific version of the .NET Framework that isn't present on the system, it can cause issues like this. Ensuring that the required version of the .NET Framework is installed and configured correctly might resolve the issue.

2. **Missing Resources**: If the application is looking for resources (like DLLs, configuration files, or other dependencies) that aren't found in the expected locations, it could fail to load parts of the interface or certain features properly.

3. **Corrupted Installation**: The application or its components might be corrupted. Reinstalling the application could fix this.

4. **Configuration Issues**: If there are configuration files that the Dash Manager relies on, and these files are either missing, corrupted, or contain invalid data, this could cause the application to not function correctly.

5. **Software Conflict**: There could be a conflict with other software installed on the system, such as antivirus software or other VR-related tools.

6. **Permissions**: The application might not have the necessary permissions to access certain resources on the computer, leading to incomplete functionality.

7. **User Settings**: Sometimes user settings within the application can lead to certain features not working as expected. Resetting user preferences or settings to default might help.

To troubleshoot the issue, consider the following steps:

- Verify the application is up to date and compatible with the current .NET Framework installed on your system.
- Check the application logs (if available) for any error messages that could give a clue as to what is failing.
- Ensure all required dependencies and resources are correctly placed and accessible by the application.
- Try running the application with administrator privileges to rule out permission issues.
- Temporarily disable any antivirus or firewall software to rule out conflicts, then re-enable them.

**Comment by H4rrisonFart** [comment] 2023-11-24 14:04
Thank you for your detailed assistance! First I just completely deleted Oculus Killer + Oculus Dash and reinstalled them. That made everything worse. Then I deleted everything, including the original Oculus software, and only reinstalled your dashboard (without Oculus Killer) + Oculus software. Now the dashboard works without these strange visual distortions. Of course, Oculus Killer no longer works. I'm a little unsure whether I should try inserting the OculusKiller.exe again as described... but I'll try it again this evening. And then I'll report back how it went.

**Comment by Eliminater74** [comment] 2023-11-24 19:49
> Thank you for your detailed assistance! First I just completely deleted Oculus Killer + Oculus Dash and reinstalled them. That made everything worse. Then I deleted everything, including the original Oculus software, and only reinstalled your dashboard (without Oculus Killer) + Oculus software. Now the dashboard works without these strange visual distortions. Of course, Oculus Killer no longer works. I'm a little unsure whether I should try inserting the OculusKiller.exe again as described... but I'll try it again this evening. And then I'll report back how it went.


Hello,

Thank you for reaching out and sharing your experience with the Oculus VR Dash Manager. I'm glad to hear that reinstalling the dashboard and Oculus software resolved the issue with the visual distortions. It seems that a fresh installation helped to clear up any conflicts or corrupted files that might have been causing problems.

Regarding the Oculus Killer, I understand your hesitation given the issues you've encountered. Here's a step-by-step approach you might consider:

1. **Backup**: Before proceeding, ensure you have backups of your current working setup. This way, you can always revert back if needed.

2. **Reinstall Oculus Killer**: Proceed with the installation of Oculus Killer as previously described. Make sure to follow the instructions carefully to avoid any conflicts with the Oculus software or the dashboard.

3. **Monitor Performance**: After installation, monitor the performance and functionality of both the dashboard and Oculus Killer. Pay special attention to any changes or irregularities.

4. **Troubleshooting**: If you encounter any issues, try to identify the specific conditions under which they occur. This information can be crucial for troubleshooting.

5. **Seek Support**: If problems persist, feel free to reach out with detailed descriptions of the issues. The more specific you can be about what you're experiencing, the better I can assist.

6. **Stay Updated**: Keep an eye on updates for both the Oculus VR Dash Manager and Oculus Killer, as updates may contain fixes or improvements that could resolve your issues.

Remember, your feedback is invaluable in improving the overall user experience. I'm here to assist, so don't hesitate to report back after your trial this evening. Your insights not only help in addressing your concerns but also contribute to enhancing the software for all users.

Best regards,
Eliminater74

PS: I am not sure people know this, but the Dash Manager will auto install OculusKiller upon First Loading it. but when I mean when I say Auto install, it will put the OculusKiller in the Dash Directory and when you switch to OculusKiller it renames the original and replaces it with the OculusKiller, then when you go back it renames vise versa.

**Comment by H4rrisonFart** [comment] 2023-11-24 21:17
Damn...just came home, started my PC and then the problem appears again. The text at the buttons in your Dash Manager disappearing if I hover over them with the courser just like before. I didn't change anything in between. Just messed around with NirCmd changing display resolution to rly low settings with command prompt (just für curiosity not theme related). And was a little bit disappointed that it didn't work backwards. I guess cause NirCmd is to old and dind't know modern display specs (?) so i changed them back manually. I can't imagine how this should have effected the dash manager (wasnt even running at the time)?  

My Specs: OS: Win11x64 Education Pro; CPU: AMD Ryzen 9 5900X 12-Core; GPU: AMD Radeon RX 7900 XTX; RAM: 32 GB 2666 MHz DDR4 (2x16GB); MB: MSI MAG B550 TOMAHAWK; Display: 27 Zoll, 4k, HDR 10, 10Bit, 160Hz; VR: Meta Quest 3 via Link Cable USB 3.2 Gen 2
 
All Runtimes and drivers installed and up to date. All software and windows too. Everyting else works as intended. I recognized that AMD Software: Adrenaline Edition (GPU Panel) marked the oculus software as a game. I removed it from the Driver Panel but it did nothing. Also i messed around with high priority in the taskbar and set it to high performance in the windows settings without any impact. Ofc also started the dash as an admin and Antivirus Software or Win Firewall didn't block anything oculus related. I even whitelisted oculus.exe + dashboard.exe. Also used CC Cleaner to scan für Registry Failures and cleaned them. Between all this I also restarted my PC. In case I missed any essential font even downloaded "Windows-11-21h2-complete-font-collection". Then I used the command "sfc/scannow" in command prompt. It is is used to repair corrupted Windows system image files. It found something and repaired it but wihtout impact on my problem. Last I run "DISM.exe /Online /Cleanup-image /Restorehealth", also no results for Dash Manager. Idk what to try else. I could imagine that I have too many (old) runtimes installed and that causes the problems somehow? But if so, how to find out which one I should delete? Not difficult to see how noob I am^^. And cause my problem isn't rly essential (PCVR is working) and seems to be a rare individual issue, consider not waste too much of your time for me pls! 
From now on, I will make regular backups! And reinstall everything again tomorrow. I will report. Thank you for your support!

**Comment by Eliminater74** [comment] 2023-11-25 12:37
Thank you for reaching out and providing such a detailed account of the issue you're experiencing with the Dash Manager. Please rest assured, addressing your concerns is important to us, and we appreciate the opportunity to assist you in resolving this matter.

I understand the frustration that comes with encountering unexpected software behavior, especially when it seems to arise without any clear cause. Your detailed description of the steps you've taken to troubleshoot the issue is commendable and provides valuable insight.

Regarding the issue at hand, we are currently in the process of finalizing a new release of the Dash Manager. This upcoming version includes several enhancements aimed at improving stability and user experience:

1. **Framework Checks:** The new release will actively check for necessary frameworks to ensure compatibility and smooth operation.

2. **Missing File Notification:** Users will be notified if the 'OculusKiller' file is absent from its designated directory, streamlining the troubleshooting process.

3. **Code Refactoring:** We've undertaken significant code refactoring, eliminating redundant functions and optimizing existing ones. This should enhance the overall performance and reliability of the application.

As for the concern regarding old runtimes, it's a complex area that can vary significantly between systems. While we haven't observed similar issues on our test systems, including a setup with a Ryzen 5700X and Windows 11 Pro, we acknowledge that software behavior can be influenced by a myriad of factors unique to each user's configuration.

In your case, the use of tools like NirCmd and NTLite, and the modifications made to your system, could potentially contribute to the issues you're experiencing. However, without a direct examination, it's challenging to pinpoint the exact cause.

Please know that your situation is not considered a waste of our time. On the contrary, it provides us with valuable feedback and helps us improve our software. We are committed to investigating this issue thoroughly and would greatly appreciate your continued cooperation and patience.

Once the new release is available, I encourage you to try it and share your feedback. Should the problem persist, we'll delve deeper to identify and rectify the underlying cause.

Thank you once again for your support and for being a part of our community. We look forward to resolving this issue to your satisfaction.

Best regards,

Eliminater74

**Comment by H4rrisonFart** [comment] 2023-11-28 12:00
Additional Infos first: 

- Sidelink was installed and the Developermode is activatet in my HMD (it was all the time, forgot to mention it), but it worked  with it +Sidelink wasn't opened during all this deinstalled it too,  just in case..
- same as "OpenXR Toolkit Companion app", but I didn't create any profiles there neither used it, I've also checked the "Disable the   Toolkit" box and deinstalled it but without results
- clicking the Buttons worked but the Text on it disappeared instantly if I move the Mouse Cursor on it (idk if this was clear)
- Steam only (Oculus Killer) still hasn't worked as described. Steam VR started kind of but wasn't able to find link connection. But the "roll-over-issue" first felt more important for me
- in the opened "Other Tools" Window the Button Texts aren't disappeared except the two Buttons in the "ADB Menu" ("Install APK"+"ADB File Manager")
- I deleted all NirCmd files in the Registry
- I activated Admin Account with "net user administrator" 

Problem solved:
Finally something rly strange happend. My free version antivirus software want to sell additional plugins and was advertising their driver updater. That's how i recocnized a missing one. Not the official AMD-Software-Kits, neither the MSI Support Website (my Mainboard Vendor) and nor the Driver Updater I used, were able to find/deliver the **updated "AMD SMBus Driver" needed**. So I updated it manually and while some driver in this Chipset-Driver-Package were already outdatet and others already installed on my system, this one rly wasn't! 
Reinstalled everything again and it worked finally! Then a Message about your update poped up. So i tryed to replace the old unpacked folder wtih the new one. But Windows kept saying "No Permission to change". So I logged in in the System-Admin-Account and changed it there without out problems. Then I went back to my standard user profile (also with Adnmin status), started the Dashmanger and...the strange optical behavior was there again.
So I started from the system restore point i created during everything worked fine. This time **I deleted the old installation manually and checked that I couldn't deltete ADB Folder not cause I got no permisssions either just cause "adb.exe" was still running. Closed it in the Taskmanager (+OVS Service like always), replaced it and since then it works fine again!**       



I'll still reinstall Sidelink and see if it causes any problems. And I didn't have time to play anything for really long either ^^

**Thank you for your support and the great work on this project!** People like you are saving PCVR, I will donate to you in December!

**Comment by Eliminater74** [comment] 2023-11-28 14:21
Thank you for taking the time to provide such detailed feedback and for sharing your troubleshooting journey with us. It's always enlightening to hear about the unique experiences and challenges users face, as it helps us improve and adapt our tools to better serve the community.

I'm relieved to hear that you were able to resolve the issues, particularly with the AMD SMBus Driver update. It's fascinating how often overlooked components like these can have a significant impact on the functionality of more complex software systems. Your persistence and thorough approach in troubleshooting are commendable.

Also, I appreciate your efforts in experimenting with different settings and configurations, including the use of Sidelink and the OpenXR Toolkit Companion app. Your insights on these interactions are invaluable and will certainly be useful for future updates and for other users experiencing similar issues.

Regarding the optical behavior you mentioned, it's intriguing and something we'll keep an eye on. If you encounter any further issues or have additional insights, please don't hesitate to share them. User feedback is a crucial part of our development process.

Lastly, I'm glad to hear that the project has been of value to you. It's always rewarding to hear that our work is making a positive impact on the PCVR community. We're here to support and enhance your VR experience, so your acknowledgment means a lot to us.

Thank you once again for your support and for being a part of our community. We're looking forward to continuing to improve and evolve with your help.

Best regards,
Eliminater74

**Comment by Eliminater74** [comment] 2023-12-05 23:07
Issue resolved

**Closed as completed by Eliminater74** 2023-12-05 23:07 UTC
